apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: awvlk5bli-go
  janus-idp.io/tekton: awvlk5bli-go
  backstage.io/kubernetes-id: awvlk5bli-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: awvlk5bli-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
