apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: awvlk5bli-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: awvlk5bli-go 
  name: awvlk5bli-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: awvlk5bli-go 
